name: production-deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and authenticate
        run: |
          sudo tailscaled &
          sleep 3
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          sleep 5

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Docker container
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          cd /home/tnqbao/Green_MindMap_Backend

          docker pull iamqbao/green_mind_backend:latest
          docker rm -f green-mind-backend || true

          docker run -d \
            --name green-mind-backend \
            --env-file .env \
            --network green-mindmap-net \
            -p 3000:3000 \
            iamqbao/green_mind_backend:latest

          EOF
